### ISSUE TITLE
POS tag behaviour

### ISSUE THREAD

**Issue by arademaker** [own-pt/sensetion.el#128]
cases for 'italian':

- (n) Andrea Palladio,Palladio | highly original and much imitated Italian architect ( 1508 1580 ) ; 

it has POS NNP, once I annoted as ADJ, the superscript changed to `a1`

- (n) disfiguration,disfigurement,defacement | the act of damaging the appearance or surface of something ; the defacement of an Italian mosaic during the Turkish invasion ; he objected to the dam's massive disfigurement of the landscape ; 

it had no POS, once annotated it got the superscript `a1`

- (n) boccie,bocci,bocce | ItalianJJ1, bowling played on a long narrow dirt court ; 

it had the POS JJ, once I annoted it got the superscript `JJ1`? I expect `a1` too.

**Comment by arademaker** [comment]
Hum, it only happens with tokens with the sense `purposefully_ignored` !! Strange.

**Comment by odanoburu** [comment]
the rule for PoS tag display is the following:

1. if all the senses assigned to a token are for the same PoS tag, show that;
2. if not, show the token's PoS tag from corpus data, if present.

hence why  

>  it only happens with tokens with the sense `purposefully_ignored`

that's because `purposefully_ignored` has no PoS tag. (I thought we had gotten rid of them.)

if we follow through with your suggestion at #130, there should be no case where 1 happens.

**Comment by arademaker** [comment]
Case 2 is INVALID! We should not allow the annotation of senses from different PoS! OK, this will be #130 , right?

**Comment by odanoburu** [comment]
yes!
