### ISSUE TITLE
diff between import vs export file from corpus 

### ISSUE THREAD

**Issue by arademaker** [own-pt/sensetion.el#176]
- I produced the json from the plists
- I imported the file in mongodb.
- I annotated only 1 sense
- I exported mongodb to a json

```
sort ../data/mongo/glosstag.json > orig.json
sort glosstag.1.json > anot.json
diff orig.json anot.json
```

why the diff between the json imported into mongodb and the exported shows a LOT of differences?

**Comment by arademaker** [comment]
diff is also huge without the sort

**Comment by odanoburu** [comment]
sorting using `sort` doesn't work since it only reorders lines, and we might want to reorder pairs in a json dictionary.

running

```sh
jq -s -S -c 'sort_by(._id)[]' glosstag.json > glosstag-ordered.json
```

-`-s`: read all lines into array 
-`-S`: sort keys
-`-c`: compact (versus pretty-printed) output

I've followed your steps here and it shows the expected output ~minus a small bug in alist<->json conversion (in the sense that what used to be an array of arrays of two elements was converted to a dictionary, which is isomorphic but will cause spurious diffs.) this doesn't affect functionality since it only happens in one of the meta fields of the glosstag conversion. I'll fix this but it's probably due to common lisp and emacs lisp treating the conversion differently.~ (this has been fixed)
