### ISSUE TITLE
unglobbing bug

### ISSUE THREAD

**Issue by arademaker** [own-pt/sensetion.el#48]
calciferous | bearing or producing or containing bcalcium or acalcium a,bcarbonate or calcite ;

during the annotation of calcium_carbonate ~> carbonate is not green.

it is also not showing the senses of the already annotated entries.

**Comment by arademaker** [comment]
this case is an error in the MWE. The unglobbing didn't work, the `carbonate` word kept the index.

**Comment by odanoburu** [comment]
b4347bc almost closes this; I'm just debatting whether this 

> during the annotation of calcium_carbonate ~> carbonate is not green.

is a bug or a feature.

I thought it a feature because it would disallow us to annotated a token which is ambiguous like in the case we saw above; but the case above is wrong, so I wonder if this ever happens correctly. what  do you think @arademaker ? (for it to happen, we'd have to have the situation above, two collocations with the same lemma which share a token)

**Comment by arademaker** [comment]
Não lembro exatamente a situação agora, mas se carbonete não fazia parte de glob, e estávamos anotando o glob, realmente ele não deveria ficar verde

**Comment by arademaker** [comment]
Não entendi o seu uso de ambiguous acima

**Comment by odanoburu** [comment]
> (a) calciferous | bearing or producing or containing calcium or calcium carbonate or calcite ;

the example was this one; the original glossa tag corpus (erroneously) says that both `calcium`s are part of a `calcium_carbonate` glob, so we have two globs with the same lemma and which share a token. because of this, `carbonate` was not highlighted, but both calciums were. the question is: do we want to highlight tokens which are part of more than one glob which are being annotated? (notice that there's no problem if the token is shared between two globs but only one of them is being annotated, i.e., they have different lemmas) does this even happen (ignoring errors) ?

**Comment by arademaker** [comment]
The current model is

> bearing or producing or containing bcalcium or acalcium b,acarbonate or calcite ;

if we assume that both globs are right, carbonate is not highlighted because one cannot distingue the glob by selecting the cabonate.
