### ISSUE TITLE
synset r00045607 in adv file

### ISSUE THREAD

**Issue by arademaker** [own-pt/sensetion.el#68]
If I call `sensetion-annotation addition RET` this synset is not listed? If I call `sensetion-annotation beyond RET` this synset is listed! 

The XML file we have

```
   <def id="r00045607_d">
    <wf id="r00045607_wf1" lemma="in" pos="IN" tag="ignore">in</wf>
    <wf id="r00045607_wf2" lemma="addition%1" pos="NN" sep="" tag="man">
     <id id="r00045607_id.2" lemma="purposefully ignored" sk="purposefully_ignored%0:00:00::"/>addition</wf>
    <wf id="r00045607_wf3" pos=":" tag="ignore" type="punc">;</wf>
   </def>
```

but in the plist file we have only

```
  (:form "addition" :lemma "addition%1" :pos "NN" :anno nil :status "skip"
   :kind :wf :meta ((:id "wf2")))
```

Does the XML say that the token should be ignored? How can I reannotate it if the interface does not list when I ask for annotate `addition`? 

How can we mark 'ignore' in the interface? Does it make sense to have this status if we have `no sense in PWN`? In that case, one can think of `in addition` as a missing MWE in PWN. This MWE could be at http://wnpt.sl.res.ibm.com/wn/synset?id=00047534-r . So I would like to make a glob and say `no sense`.

Why are we using another status, the `skip`? How to change this status for something else? I would like to minimize changes in the original annotation schema.

**Comment by odanoburu** [comment]
> Why are we using another status, the skip? 

all instances of tokens in the original XML which had the tag `man` but didn't have any senses (where `purposefully_ignored` means no sense too) ended up with this `skip` tag. at the time of this decision I thought that the `purposefully_ignored` thing meant that the token should be ignored.

> How to change this status for something else?

 it makes sense for us to turn them into `man` tokens with no sense, or if want to have things explicit, a new `nosense` status. we can do this when fixing #71 

> How can I reannotate it if the interface does not list when I ask for annotate addition?

and yes, the tokens are not indexed because of their `skip` status; if we changed it to `man` they would be indexed for annotation.

> How can we mark 'ignore' in the interface? Does it make sense to have this status if we have no sense in PWN?

for now, manually. but I'll add a command (sooner rather than later if you find it to be a priority). yes, if we find a token that should not be part of PWN (like a pronoun); but I'm not sure we'll find cases like this..

**Comment by odanoburu** [comment]
closing this as there's no `skip` status anymore
